In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
df = pd.read_csv("/content/drive/MyDrive/survey_results_public.csv")
df.head()

Respondent                                         MainBranch Hobbyist  \
0           1                     I am a developer by profession      Yes   
1           2                     I am a developer by profession       No   
2           3                        I code primarily as a hobby      Yes   
3           4                     I am a developer by profession      Yes   
4           5  I used to be a developer by profession, but no...      Yes   

    Age Age1stCode CompFreq  CompTotal  ConvertedComp             Country  \
0   NaN         13  Monthly        NaN            NaN             Germany   
1   NaN         19      NaN        NaN            NaN      United Kingdom   
2   NaN         15      NaN        NaN            NaN  Russian Federation   
3  25.0         18      NaN        NaN            NaN             Albania   
4  31.0         16      NaN        NaN            NaN       United States   

     CurrencyDesc  ...                  SurveyEase           SurveyLength  \
0   European Euro  ...  Neither easy nor difficult  Appropriate in length   
1  Pound sterling  ...                         NaN                    NaN   
2             NaN  ...  Neither easy nor difficult  Appropriate in length   
3    Albanian lek  ...                         NaN                    NaN   
4             NaN  ...                        Easy              Too short   

  Trans                                     UndergradMajor  \
0    No  Computer science, computer engineering, or sof...   
1   NaN  Computer science, computer engineering, or sof...   
2   NaN                                                NaN   
3    No  Computer science, computer engineering, or sof...   
4    No  Computer science, computer engineering, or sof...   

  WebframeDesireNextYear    WebframeWorkedWith  \
0           ASP.NET Core  ASP.NET;ASP.NET Core   
1                    NaN                   NaN   
2                    NaN                   NaN   
3                    NaN                   NaN   
4   Django;Ruby on Rails         Ruby on Rails   

                              WelcomeChange WorkWeekHrs YearsCode YearsCodePro  
0   Just as welcome now as I felt last year        50.0        36           27  
1  Somewhat more welcome now than last year         NaN         7            4  
2  Somewhat more welcome now than last year         NaN         4          NaN  
3  Somewhat less welcome now than last year        40.0         7            4  
4   Just as welcome now as I felt last year         NaN        15            8  

[5 rows x 61 columns]

In [ ]:
#Country
#Educational level
#Employment
#Year of Exp
#Salary

In [ ]:
df = df[['Country','EdLevel','Employment','YearsCodePro','ConvertedComp']]

In [ ]:
df.shape

(64461, 5)

In [ ]:
df  = df.rename({"ConvertedComp":"Salary"},axis = 1)

In [ ]:
df.head()

Country                                          EdLevel  \
0             Germany  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
1      United Kingdom     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
2  Russian Federation                                              NaN   
3             Albania  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
4       United States     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   

                                          Employment YearsCodePro  Salary  
0  Independent contractor, freelancer, or self-em...           27     NaN  
1                                 Employed full-time            4     NaN  
2                                                NaN          NaN     NaN  
3                                                NaN            4     NaN  
4                                 Employed full-time            8     NaN

In [ ]:
df = df[df['Salary'].notnull()]
df.shape

(34756, 5)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34756 entries, 7 to 64154
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Country       34756 non-null  object 
 1   EdLevel       34188 non-null  object 
 2   Employment    34717 non-null  object 
 3   YearsCodePro  34621 non-null  object 
 4   Salary        34756 non-null  float64
dtypes: float64(1), object(4)
memory usage: 1.6+ MB


In [ ]:
df.isnull().sum()

Country           0
EdLevel         568
Employment       39
YearsCodePro    135
Salary            0
dtype: int64

In [ ]:
df = df.dropna()
df.isnull().sum()

Country         0
EdLevel         0
Employment      0
YearsCodePro    0
Salary          0
dtype: int64

In [ ]:
df.sample(5)

Country                                          EdLevel  \
3892   United States  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
23966      Indonesia     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
4277       Australia     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
16819         France  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
328    United States     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   

               Employment YearsCodePro     Salary  
3892   Employed full-time            8  1380000.0  
23966  Employed full-time            2     3516.0  
4277   Employed full-time           15    86853.0  
16819  Employed full-time            2    36753.0  
328    Employed full-time            5   115000.0

In [ ]:
#only full time employees to be considered
df  = df[df['Employment'] == 'Employed full-time']
df.shape


(30019, 5)

In [ ]:
df.drop(columns = ['Employment'],inplace = True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30019 entries, 7 to 64154
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Country       30019 non-null  object 
 1   EdLevel       30019 non-null  object 
 2   YearsCodePro  30019 non-null  object 
 3   Salary        30019 non-null  float64
dtypes: float64(1), object(3)
memory usage: 1.1+ MB


In [ ]:
df['Country'].value_counts()

Country
United States     7569
India             2425
United Kingdom    2287
Germany           1903
Canada            1178
                  ... 
Benin                1
Fiji                 1
San Marino           1
Guinea               1
Andorra              1
Name: count, Length: 154, dtype: int64

In [ ]:
#only consider countries which appeared more than 400 times

df = df[df.groupby(["Country"])['Country'].transform('count')> 400]

In [ ]:
df['Country'].value_counts()

Country
United States         7569
India                 2425
United Kingdom        2287
Germany               1903
Canada                1178
Brazil                 991
France                 972
Spain                  670
Australia              659
Netherlands            654
Poland                 566
Italy                  560
Russian Federation     522
Sweden                 514
Name: count, dtype: int64

In [ ]:
df.sample(5)

Country                                          EdLevel  \
10190           India     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
56184  United Kingdom  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
3622    United States     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
34391   United States     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
31906         Germany  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   

           YearsCodePro     Salary  
10190                 2     9075.0  
56184                 5   729024.0  
3622   Less than 1 year    85000.0  
34391                19  1272000.0  
31906                 5    59454.0

In [ ]:
# only consider people with salary between 10,000 and 250000
df = df[df['Salary'] >= 10000]
df = df[df['Salary'] <= 250000]

In [ ]:
df.shape

(18491, 4)

In [ ]:
df.sample(5)

Country                                          EdLevel  \
16319       United States  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
48916              Sweden  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
18693       United States  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
9411   Russian Federation  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
54143               India     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   

      YearsCodePro    Salary  
16319           20  200000.0  
48916            5   49092.0  
18693            9   79576.0  
9411            20   39300.0  
54143            3   11728.0

In [ ]:
df['YearsCodePro'].unique()

array(['13', '4', '2', '7', '20', '1', '3', '10', '12', '29', '6', '28',
       '8', '23', '15', '25', '9', '11', 'Less than 1 year', '5', '21',
       '16', '18', '14', '32', '19', '22', '38', '30', '26', '27', '17',
       '24', '34', '35', '33', '36', '40', '39', 'More than 50 years',
       '31', '37', '41', '45', '42', '44', '43', '50', '49'], dtype=object)

In [ ]:
#will filter data for experience

def filter_exp(x):
  if x ==  'More than 50 years':
    return 50
  if x == 'Less than 1 year':
    return 0.5
  return float(x)

In [ ]:
filter_exp('More than 50 years')

50

In [ ]:
df['YearsCodePro'] = df['YearsCodePro'].apply(filter_exp)

In [ ]:
df['YearsCodePro'].unique()

array([13. ,  4. ,  2. ,  7. , 20. ,  1. ,  3. , 10. , 12. , 29. ,  6. ,
       28. ,  8. , 23. , 15. , 25. ,  9. , 11. ,  0.5,  5. , 21. , 16. ,
       18. , 14. , 32. , 19. , 22. , 38. , 30. , 26. , 27. , 17. , 24. ,
       34. , 35. , 33. , 36. , 40. , 39. , 50. , 31. , 37. , 41. , 45. ,
       42. , 44. , 43. , 49. ])

In [ ]:
df.sample(5)

Country                                            EdLevel  \
92            Canada  Some college/university study without earning ...   
8503           Spain                Associate degree (A.A., A.S., etc.)   
14345        Germany       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
25332  United States    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
11642         France    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   

       YearsCodePro   Salary  
92              2.0  37816.0  
8503            5.0  21620.0  
14345          11.0  71345.0  
25332           2.0  75000.0  
11642           5.0  64859.0

In [ ]:
df['EdLevel'].unique()

array(['Bachelor’s degree (B.A., B.S., B.Eng., etc.)',
       'Master’s degree (M.A., M.S., M.Eng., MBA, etc.)',
       'Some college/university study without earning a degree',
       'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)',
       'Associate degree (A.A., A.S., etc.)',
       'Professional degree (JD, MD, etc.)',
       'Other doctoral degree (Ph.D., Ed.D., etc.)',
       'I never completed any formal education',
       'Primary/elementary school'], dtype=object)

In [ ]:
def filter_education(x):
  if 'Bachelor’s degree' in x:
    return 'Bachelor’s degree'
  if 'Master’s degree' in x:
    return 'Master’s degree'
  if 'Professional degree' in x or 'Other doctoral' in x:
    return 'Post grad'
  return 'Less than a Bachelors'

In [ ]:
filter_education('I never completed any formal education')

'Less than a Bachelors'

In [ ]:
df['EdLevel'] = df['EdLevel'].apply(filter_education)

In [ ]:
df.sample(5)

Country            EdLevel  YearsCodePro   Salary
35071          France    Master’s degree           5.0  61616.0
13558  United Kingdom  Bachelor’s degree           3.0  31643.0
11302           India  Bachelor’s degree           4.0  70368.0
29009          France    Master’s degree           0.5  32429.0
25236   United States  Bachelor’s degree           1.0  80000.0

In [ ]:
df['Country'].unique()

array(['United States', 'United Kingdom', 'Spain', 'Netherlands',
       'Germany', 'Canada', 'Italy', 'Brazil', 'France', 'India',
       'Sweden', 'Poland', 'Australia', 'Russian Federation'],
      dtype=object)

In [ ]:
# Will convert high level language to machine understandable i.e. encoder

In [ ]:
from sklearn.preprocessing import LabelEncoder
le_country = LabelEncoder()


In [ ]:
df['Country'] = le_country.fit_transform(df['Country'])
df['Country'].unique()

array([13, 12, 10,  7,  4,  2,  6,  1,  3,  5, 11,  8,  0,  9])

In [ ]:
list(le_country.inverse_transform([9]))

['Russian Federation']

In [ ]:
df.sample()

Country            EdLevel  YearsCodePro   Salary
7359       13  Bachelor’s degree           2.0  63000.0

In [ ]:
le_education = LabelEncoder()
df['EdLevel'] = le_education.fit_transform(df['EdLevel'])
df['EdLevel'].unique()


array([0, 2, 1, 3])

In [ ]:
list(le_education.inverse_transform([2]))

['Master’s degree']

In [ ]:
df.head()

Country  EdLevel  YearsCodePro    Salary
7        13        0          13.0  116000.0
9        12        2           4.0   32315.0
10       12        0           2.0   40070.0
11       10        1           7.0   14268.0
12        7        1          20.0   38916.0

In [ ]:
#defining input and output columns
X = df[['Country',	'EdLevel','YearsCodePro',]]
X

Country  EdLevel  YearsCodePro
7           13        0          13.0
9           12        2           4.0
10          12        0           2.0
11          10        1           7.0
12           7        1          20.0
...        ...      ...           ...
64113       13        1          15.0
64116       13        0           6.0
64122       13        1           4.0
64127       13        3          12.0
64129       13        2           4.0

[18491 rows x 3 columns]

In [ ]:
y = df[['Salary']]
y

Salary
7      116000.0
9       32315.0
10      40070.0
11      14268.0
12      38916.0
...         ...
64113  225000.0
64116  150000.0
64122   70000.0
64127  140000.0
64129  150000.0

[18491 rows x 1 columns]

In [ ]:
from sklearn.linear_model import LinearRegression
linear_reg = LinearRegression()

In [ ]:
linear_reg.fit(X,y)

LinearRegression()

In [ ]:
y_pred = linear_reg.predict(X)

In [ ]:
df.sample()

Country  EdLevel  YearsCodePro   Salary
6501        5        0           4.0  11169.0

In [ ]:
linear_reg.predict([[2,1,1]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[29478.99934055]])

In [ ]:
X = np.array([['United States','Post grad',15]])
X

array([['United States', 'Post grad', '15']], dtype='<U21')

In [ ]:
X[:,0] = le_country.transform(X[:,0])
X[:,1] = le_education.transform(X[:,1])
X = X.astype(float)
X

array([[13.,  3., 15.]])

In [ ]:
linear_reg.predict(X)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[107970.46174556]])

In [ ]:
import pickle

In [ ]:
data = {'model':linear_reg,'le_country':le_country,'le_education':le_education}
with open('deployment.pkl','wb') as file:
  pickle.dump(data,file)

In [ ]:
with open('deployment.pkl','rb') as file:
  data = pickle.load(file)

  model = data['model']
  le_country = data['le_country']
  le_education = data['le_education']

y_pred = linear_reg.predict(X)
y_pred

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[107970.46174556]])

In [ ]:
!pip install streamlit

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 20.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.3/207.3 kB 19.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 49.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.0/83.0 kB 9.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 7.0 MB/s eta 0:00:00


In [ ]:
%%writefile app.py
import streamlit as st
import pickle
import numpy as np



def load_model():
  with open('deployment.pkl','rb') as file:
    data = pickle.load(file)
  return data

data = load_model()

model = data['model']
le_country = data['le_country']
le_education = data['le_education']

st.title("Salary Prediction")



countries = (
    'United States',
    'India',
    'United Kingdom',
    'Germany',
    'Canada',
    'Brazil',
    'France',
    'Spain',
    'Netherlands',
)

education = (
    'Less than a Bachelors',
    'Bachelor’s degree',
    'Master’s degree',
    'Post grad',
)

country = st.selectbox("Country",countries)
education = st.selectbox("Education Level",education)
experience = st.slider("Years of Experience",0,50)

ok = st.button("Calculate Salary")
if ok:
  X = np.array([[country,education,experience]])
  X[:,0] = le_country.transform(X[:,0])
  X[:,1] = le_education.transform(X[:,1])
  X = X.astype(float)
  salary = model.predict(X)
  st.subheader("The Estimated Salary is ₹"+str(round(salary[0][0])))

Writing app.py


In [ ]:
!streamlit run app.py & npx localtunnel --port 8501




  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://35.227.172.37:8501

npx: installed 22 in 6.94s
your url is: https://thin-papers-dig.loca.lt
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
